# Generated by Django 2.2 on 2019-05-03 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='plot',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='short_plot',
            field=models.CharField(max_length=300),
        ),
        migrations.AddField(
            model_name='moviemedia',
            name='media_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.MediaType'),
        ),
    ]
