# Generated by Django 2.2 on 2019-05-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20190503_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviemedia',
            name='video_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
